baseURL = "http://localhost:1313/"
languageCode = "en"
defaultContentLanguage = "en"    # en / fr / ... (This field determines which i18n file to use)
title = "Processing for Pi"
enableRobotsTXT = true
enableEmoji = true
theme = "kube"

preserveTaxonomyNames = true
paginate = 10             # how many pages to show
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name

[author]                  # essential
  name = "Maks Surguy"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu
  name = "Welcome"
  weight = 10
  identifier = "welcome"
  url = "/welcome/"
[[menu.main]]
  name = "Get Started"
  weight = 20
  identifier = "get-started"
  url = "/get-started/"
[[menu.main]]
  name = "Download"
  weight = 30
  identifier = "download"
  url = "/download/"
#[[menu.main]]
#  name = "Tutorials"
#  weight = 40
#  identifier = "tutorials"
#  url = "/tutorial/"

[[menu.main]]
  name = "Reference"
  weight = 50
  identifier = "reference"
  url = "/reference/"

[[menu.main]]
  name = "Libraries"
  weight = 60
  identifier = "libraries"
  url = "/libraries/"


[[menu.main]]
  name = "Social"
  weight = 70
  identifier = "social"
  url = "/social/"


[[menu.main]]
  name = "Imprint"
  weight = 80
  identifier = "imprint"
  url = "/imprint/"


[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

  since = "2018"            # Site creation date

  # site info (optional)
  logoTitle = "Processing"        # default: the title value
  keywords = ["processing", "raspberry pi"]
  description = "Processing for Pi"

  # paginate of archives, tags and categories
  archivePaginate = 5

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?
  moreMeta = false

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true
  autoCollapseToc = false   # Auto expand and collapse toc
  fancybox = true           # see https://github.com/fancyapps/fancybox

  postMetaInFooter = true   # contain author, lastMod, markdown link, license
  linkToMarkDown = false    # Only effective when hugo will output .md files
  contentCopyright = ''     # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  google_verification = ""  # Google_Verification

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

  [params.social]
    a-email = "mailto:your@email.com"
    c-twitter = "http://localhost:1313"
    d-facebook = "http://localhost:1313"
    f-google = "http://localhost:1313"
    g-github = "http://localhost:1313"

# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffix = "md"
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
